# Generated by Django 3.2.6 on 2021-08-05 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cottage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('bedrooms', models.IntegerField()),
                ('booked', models.BooleanField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.TextField()),
                ('description', models.TextField()),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cottage')),
            ],
        ),
        migrations.CreateModel(
            name='CottageImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, max_length=30, null=True)),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='')),
                ('cottage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cottage')),
            ],
        ),
    ]
