# Generated by Django 3.2.6 on 2021-08-05 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cottage',
            old_name='available_bedrooms',
            new_name='bedrooms',
        ),
        migrations.RenameField(
            model_name='cottage',
            old_name='cottage_booked',
            new_name='booked',
        ),
        migrations.RemoveField(
            model_name='cottage',
            name='number_of_bedrooms',
        ),
    ]
